import {TYPES,BUCKETS,metrics,accountBalances,position,distribution,goalSaved,loanBalance,debtBalance,duePayments,convert,today} from './core.js';
const enc=new TextEncoder();
const xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const col=n=>{let x='';for(n++;n;n=Math.floor((n-1)/26))x=String.fromCharCode(65+(n-1)%26)+x;return x;};
function crc32(a){let c=0xffffffff;for(const b of a){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function zip(files){const parts=[],central=[];let offset=0;const u16=(v,o,n)=>v.setUint16(o,n,true),u32=(v,o,n)=>v.setUint32(o,n,true);for(const [name,text] of files){const n=enc.encode(name),data=enc.encode(text),crc=crc32(data);const a=new Uint8Array(30+n.length),v=new DataView(a.buffer);u32(v,0,0x04034b50);u16(v,4,20);u16(v,6,0x800);u32(v,14,crc);u32(v,18,data.length);u32(v,22,data.length);u16(v,26,n.length);a.set(n,30);parts.push(a,data);const b=new Uint8Array(46+n.length),w=new DataView(b.buffer);u32(w,0,0x02014b50);u16(w,4,20);u16(w,6,20);u16(w,8,0x800);u32(w,16,crc);u32(w,20,data.length);u32(w,24,data.length);u16(w,28,n.length);u32(w,42,offset);b.set(n,46);central.push(b);offset+=a.length+data.length;}const end=new Uint8Array(22),v=new DataView(end.buffer);u32(v,0,0x06054b50);u16(v,8,files.length);u16(v,10,files.length);u32(v,12,central.reduce((n,a)=>n+a.length,0));u32(v,16,offset);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
export function workbookData(s,filters={},currency='ARS'){
 const project=id=>s.projects.find(p=>p.id===id)?.name||'Personal',account=id=>s.accounts.find(a=>a.id===id)?.name||'',m=metrics(s,filters,currency),p=position(s,currency),tx=s.transactions;
 const headers=['ID','Fecha','Mes','Año','Moneda','Tipo','Categoría','Subcategoría','Proyecto','Descripción','Importe original','Medio de pago','Cuenta','Estado','Tipo de gasto','Distribución','ARS por USD','Importe ARS','Importe USD','Destino','Importe destino','Vencimiento','ID préstamo','ID deuda','ID objetivo','Observaciones'];
 const rows=ts=>ts.map(t=>[t.id,t.date,t.date.slice(0,7),+t.date.slice(0,4),t.currency,TYPES[t.type],t.category,t.subcategory,project(t.projectId),t.description,t.amount,t.method,account(t.accountId),t.status==='confirmed'?'Confirmado':'Pendiente',t.expenseType,t.bucket,t.rate,convert(t.amount,t.currency,'ARS',t.rate),convert(t.amount,t.currency,'USD',t.rate),account(t.toAccountId),t.toAmount||0,t.dueDate||t.date,t.loanId,t.debtId,t.goalId,t.notes]);
 const tabs=[];const add=(name,heads,values)=>tabs.push({name,headers:heads,rows:values});
 add('DASHBOARD',['Indicador',`Importe ${currency}`],[['Ingresos del período',m.income],['Gastos del período',m.expense],['Resultado de caja antes de inversión',m.net],['Inversión realizada',m.investment],['Ahorro reservado neto',m.saving],['Saldo de cuentas hoy',p?.cash??'Falta cotización'],['Reservas hoy',p?.reserved??'Falta cotización'],['Comprometido 30 días y vencido',p?.due??'Falta cotización'],['Disponible luego de reservas y pagos',p?.available??'Falta cotización'],['Patrimonio financiero a costo',p?.netWorth??'Falta cotización'],['Moneda de presentación',currency],['Período',filters.month||'Todo el histórico'],['Proyecto',filters.project?project(filters.project):'Todos'],['Categoría',filters.category||'Todas'],['Fecha de exportación',today()],['Tipo de reporte','Instantánea. La aplicación es la fuente de carga.']]);
 add('INGRESOS',headers,rows(tx.filter(t=>t.type==='income')));
 add('DISTRIBUCIÓN',['Destino','Porcentaje',`Asignado ${currency}`,`Utilizado ${currency}`,`Disponible ${currency}`],distribution(s,filters,currency).map(d=>[d.name,d.percent/100,d.allocated,d.used,d.available]));
 add('GASTOS PERSONALES',headers,rows(tx.filter(t=>['expense','debt_pay'].includes(t.type)&&!t.projectId)));
 add('EMPRENDIMIENTOS',headers,rows(tx.filter(t=>['expense','debt_pay','investment'].includes(t.type)&&t.projectId)));
 add('PROYECTOS',['Proyecto',`Ingresos ${currency}`,`Gastos ${currency}`,`Inversión ${currency}`,`Ganancia ${currency}`,'ROI','Margen','Presupuesto original','Objetivo original','Moneda'],s.projects.map(p=>{const q=metrics(s,{...filters,project:p.id},currency);return[p.name,q.income,q.expense,q.investment,q.net,q.roi??'',q.margin??'',p.budget,p.target,p.currency]}));
 add('PRESUPUESTO',['Mes','Categoría','Proyecto','Moneda','Presupuesto','Real','Diferencia','Utilización','Estado'],s.budgets.map(b=>{const real=metrics(s,{month:b.month,project:b.projectId||'personal',category:b.category},b.currency).expense;return[b.month,b.category,project(b.projectId),b.currency,b.amount,real,b.amount-real,real/b.amount,real>b.amount?'Excedido':real>=b.amount*.9?'Cerca del límite':'Dentro del presupuesto']}));
 const buyHeaders=['Producto','Categoría','Prioridad','Precio estimado','Moneda','Ahorrado','Falta','Fecha objetivo','Comprado','Precio real','Fecha compra','Observaciones'];
 const buys=items=>items.map(b=>{const g=s.goals.find(g=>g.id===b.goalId);const saved=g?convert(goalSaved(s,g.id),g.currency,b.currency,s.settings.rate):0;const purchases=tx.filter(t=>t.purchaseId===b.id&&t.status==='confirmed');return[b.name,b.category,b.priority,b.estimate,b.currency,saved,Math.max(0,b.estimate-saved),b.date,b.bought?'Sí':'No',purchases.reduce((n,t)=>n+convert(t.amount,t.currency,b.currency,t.rate),0),purchases[0]?.date||'',b.notes]});
 add('CASA',buyHeaders,buys(s.purchases.filter(b=>b.category==='Casa')));add('COMPRAS PENDIENTES',buyHeaders,buys(s.purchases));
 add('TAREAS FINANCIERAS',['Tarea','Tipo','Proyecto','Coste estimado','Moneda','Fecha límite','Prioridad','Estado','Observaciones'],s.tasks.map(t=>[t.name,t.type,project(t.projectId),t.amount,t.currency,t.date,t.priority,t.status,t.notes]));
 add('PAGOS PRÓXIMOS',['Fecha','Concepto','Categoría','Proyecto','Monto','Moneda','Estado'],duePayments(s).map(t=>[t.date,t.description,t.category,project(t.projectId),t.amount,t.currency,t.state]));
 add('PRÉSTAMOS',['ID','Dirección','Persona','Fecha','Moneda','Capital inicial previo','Capital desembolsado','Devuelto','Saldo','Vencimiento','Estado','Motivo'],s.loans.map(l=>{const ts=tx.filter(t=>t.loanId===l.id&&t.status==='confirmed'&&t.date<=today());const bal=loanBalance(s,l);return[l.id,l.direction==='given'?'Por cobrar':'Por pagar',l.person,l.date,l.currency,l.initial,ts.filter(t=>['loan_given','loan_received'].includes(t.type)).reduce((n,t)=>n+t.amount,0),ts.filter(t=>['loan_collect','loan_repay'].includes(t.type)).reduce((n,t)=>n+t.amount,0),bal,l.dueDate,bal<=0?'Pagado':l.dueDate<today()?'Vencido':'Pendiente',l.reason]}));
 add('CUENTAS',['Cuenta','Tipo','Moneda','Saldo inicial','Entradas','Salidas','Saldo actual'],accountBalances(s).map(a=>[a.name,a.type,a.currency,a.initial,a.entries,a.exits,a.balance]));
 add('AHORROS',['Objetivo','Meta','Moneda','Ahorrado','Falta','Completado','Fecha objetivo','Estado'],s.goals.map(g=>{const v=goalSaved(s,g.id);return[g.name,g.target,g.currency,v,Math.max(0,g.target-v),v/g.target,g.date,v>=g.target?'Cumplido':'En progreso']}));
 add('SUSCRIPCIONES',['Servicio','Categoría','Proyecto','Precio','Moneda','Frecuencia en meses','Próxima renovación','Cuenta','Activo','Mensual ARS','Anual ARS','Mensual USD','Anual USD'],s.subscriptions.map(a=>[a.name,a.category,project(a.projectId),a.amount,a.currency,a.frequency,a.nextDate,account(a.accountId),a.active?'Sí':'No',...['ARS','USD'].flatMap(c=>{const val=a.active?convert(a.amount,a.currency,c,s.settings.rate)/a.frequency:0;return[Number.isFinite(val)?val:'Falta cotización',Number.isFinite(val)?val*12:'Falta cotización']})]));
 add('DEUDAS Y CUOTAS',['ID','Concepto','Acreedor','Importe original','Moneda','Cuotas','Cuotas equivalentes pagadas','Cuotas restantes','Valor cuota','Primer vencimiento','Saldo pendiente','Estado'],s.debts.map(d=>{const balance=debtBalance(s,d),paid=Math.floor((d.amount-balance)/d.installment);return[d.id,d.name,d.creditor,d.amount,d.currency,d.installments,paid,Math.max(0,d.installments-paid),d.installment,d.nextDate,balance,balance<=0?'Pagado':'Pendiente']}));
 add('TIPO DE CAMBIO',['Concepto','ARS por USD'],[['Cotización actual manual',s.settings.rate],['Cada movimiento conserva su propia cotización histórica.','']]);
 const year=filters.month?.slice(0,4)||today().slice(0,4);const monthly=Array.from({length:12},(_,i)=>{const mo=`${year}-${String(i+1).padStart(2,'0')}`,q=metrics(s,{...filters,month:mo},currency);return[mo,q.income,q.personal,q.business,q.fixed,q.variable,q.small,q.investment,q.saving,q.sum(['expense'],t=>t.bucket==='Estudio'),q.sum(['expense'],t=>t.bucket==='Regalos'),q.sum(['expense'],t=>t.bucket==='Caprichos'),q.sum(['loan_repay']),q.sum(['debt_pay']),q.net,q.savingRate??'',q.afterInvestment]});
 add('CIERRE MENSUAL',['Mes',`Ingresos ${currency}`,'Gasto personal','Gasto negocio','Fijos','Variables','Hormiga','Inversión','Ahorro','Estudio','Regalos','Caprichos','Préstamos pagados','Deudas pagadas','Resultado','Tasa ahorro','Después de inversión'],monthly);
 add('RESUMEN ANUAL',['Mes',`Ingresos ${currency}`,`Gastos ${currency}`,`Resultado ${currency}`,`Ahorro ${currency}`,`Inversión ${currency}`],monthly.map(r=>[r[0],r[1],r[2]+r[3],r[14],r[8],r[7]]));
 add('CONFIGURACIÓN',['Categoría','Destino','Distribución'],s.settings.categories.map((c,i)=>[c,BUCKETS[i]||'',i<6?s.settings.percentages[i]/100:'']));add('MOVIMIENTOS',headers,rows(tx));
 return tabs;
}
export function createXlsx(tabs){
 const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',rel='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
 const files=[],types=[['rels','application/vnd.openxmlformats-package.relationships+xml'],['xml','application/xml']];const overrides=[];
 const add=(name,text,type)=>{files.push([name,'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+text]);if(type)overrides.push([`/${name}`,type]);};
 add('_rels/.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="${rel}/officeDocument" Target="xl/workbook.xml"/></Relationships>`);
 add('xl/workbook.xml',`<workbook xmlns="${ns}" xmlns:r="${rel}"><bookViews><workbookView/></bookViews><sheets>${tabs.map((t,i)=>`<sheet name="${xml(t.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>`,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml');
 add('xl/_rels/workbook.xml.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${tabs.map((t,i)=>`<Relationship Id="rId${i+1}" Type="${rel}/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="styles" Type="${rel}/styles" Target="styles.xml"/></Relationships>`);
 add('xl/styles.xml',`<styleSheet xmlns="${ns}"><numFmts count="1"><numFmt numFmtId="164" formatCode="#,##0.00;[Red](#,##0.00)"/></numFmts><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF243F36"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment wrapText="1" vertical="center"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`,'application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml');
 tabs.forEach((t,i)=>{const matrix=[t.headers,...t.rows];const data=matrix.map((row,r)=>`<row r="${r+1}"${r===0?' ht="34" customHeight="1"':''}>${row.map((v,c)=>{const ref=`${col(c)}${r+1}`;return typeof v==='number'&&Number.isFinite(v)?`<c r="${ref}" s="${r===0?1:2}"><v>${v}</v></c>`:`<c r="${ref}" s="${r===0?1:0}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`}).join('')}</row>`).join('');const last=`${col(t.headers.length-1)}${Math.max(2,matrix.length)}`;
 add(`xl/worksheets/sheet${i+1}.xml`,`<worksheet xmlns="${ns}" xmlns:r="${rel}"><dimension ref="A1:${last}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="21"/><cols>${t.headers.map((h,c)=>`<col min="${c+1}" max="${c+1}" width="${Math.min(48,Math.max(18,h.length+3,...t.rows.slice(0,30).map(r=>typeof r[c]==='string'?Math.min(r[c].length+2,38):18)))}" customWidth="1"/>`).join('')}</cols><sheetData>${data}</sheetData><tableParts count="1"><tablePart r:id="table"/></tableParts></worksheet>`,'application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml');
 add(`xl/worksheets/_rels/sheet${i+1}.xml.rels`,`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="table" Type="${rel}/table" Target="../tables/table${i+1}.xml"/></Relationships>`);
 add(`xl/tables/table${i+1}.xml`,`<table xmlns="${ns}" id="${i+1}" name="Tabla${i+1}" displayName="Tabla${i+1}" ref="A1:${last}" totalsRowShown="0"><autoFilter ref="A1:${last}"/><tableColumns count="${t.headers.length}">${t.headers.map((h,j)=>`<tableColumn id="${j+1}" name="${xml(h)}"/>`).join('')}</tableColumns><tableStyleInfo name="TableStyleMedium4" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/></table>`,'application/vnd.openxmlformats-officedocument.spreadsheetml.table+xml');});
 files.push(['[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">${types.map(([e,t])=>`<Default Extension="${e}" ContentType="${t}"/>`).join('')}${overrides.map(([p,t])=>`<Override PartName="${p}" ContentType="${t}"/>`).join('')}</Types>`]);return zip(files);
}
export function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
